export const actionTypes = {
  ADD_COURSE: 'ADD_COURSE',
  DELETE_COURSE: 'DELETE_COURSE',
  LOAD_COURSE: 'LOAD_COURSE',
  EXPORT_COURSES: 'EXPORT_COURSES',
  EDIT_COURSE: 'EDIT_COURSE',
  SET_BOARD: 'SET_BOARD',
  DRAG_EVENT: 'DRAG_EVENT',
};